// Code generated by command: go run main.go -ntt -out ../../math/internal/dftops/asm_ntt_pow2.s -stubs ../../math/internal/dftops/asm_ntt_pow2_stub_amd64.go -pkg=dftops. DO NOT EDIT.

//go:build amd64 && !purego

package dftops

//go:noescape
func nttInPlacePow2UnrollAVX2(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func nttInPlacePow2UnrollAVX512(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func inttInPlacePow2UnrollAVX2(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)

//go:noescape
func inttInPlacePow2UnrollAVX512(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)
