// Code generated by command: go run main.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addLazyToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarLazyToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subLazyToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarLazyToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64)
