// Code generated by command: go run main.go -vec -out ../../math/vec/asm_ops_amd64.s -stubs ../../math/vec/asm_ops_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func addLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func subToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func subLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func bMulToAVX2(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulLazyToAVX2(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
