// Code generated by command: go run main.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func addToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·addToAVX2(SB), NOSPLIT, $0-80
	VPCMPEQQ     Y0, Y0, Y0
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Y1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(R8*8), Y2
	VMOVDQU  (SI)(R8*8), Y3
	VPADDQ   Y3, Y2, Y2
	VPCMPGTQ Y2, Y1, Y3
	VPXOR    Y0, Y3, Y3
	VPAND    Y1, Y3, Y3
	VPSUBQ   Y3, Y2, Y2
	VMOVDQU  Y2, (DX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    DI, AX
	CMOVQGE R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addLazyToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·addLazyToAVX2(SB), NOSPLIT, $0-72
	VPCMPEQQ Y0, Y0, Y0
	MOVQ     vOut_len+8(FP), AX
	MOVQ     vOut_base+0(FP), CX
	MOVQ     v0_base+24(FP), DX
	MOVQ     v1_base+48(FP), BX
	MOVQ     AX, SI
	SHRQ     $0x02, SI
	SHLQ     $0x02, SI
	XORQ     DI, DI
	JMP      loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y0
	VMOVDQU (BX)(DI*8), Y1
	VPADDQ  Y1, Y0, Y0
	VMOVDQU Y0, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·addToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z1
	VMOVDQU64 (SI)(R8*8), Z2
	VPADDQ    Z2, Z1, Z1
	VPCMPQ    $0x05, Z0, Z1, K1
	VMOVAPD.Z Z0, K1, Z2
	VPSUBQ    Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    DI, AX
	CMOVQGE R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512F
TEXT ·addLazyToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPADDQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·subToAVX2(SB), NOSPLIT, $0-80
	VPXOR        Y0, Y0, Y0
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Y1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(R8*8), Y2
	VMOVDQU  (SI)(R8*8), Y3
	VPSUBQ   Y3, Y2, Y2
	VPCMPGTQ Y2, Y0, Y3
	VPAND    Y1, Y3, Y3
	VPADDQ   Y3, Y2, Y2
	VMOVDQU  Y2, (DX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    DI, $0x00
	CMOVQLT R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subLazyToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·subLazyToAVX2(SB), NOSPLIT, $0-72
	VPXOR Y0, Y0, Y0
	MOVQ  vOut_len+8(FP), AX
	MOVQ  vOut_base+0(FP), CX
	MOVQ  v0_base+24(FP), DX
	MOVQ  v1_base+48(FP), BX
	MOVQ  AX, SI
	SHRQ  $0x02, SI
	SHLQ  $0x02, SI
	XORQ  DI, DI
	JMP   loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y0
	VMOVDQU (BX)(DI*8), Y1
	VPSUBQ  Y1, Y0, Y0
	VMOVDQU Y0, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, CMOV
TEXT ·subToAVX512(SB), NOSPLIT, $0-80
	VXORPD       Z0, Z0, Z0
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z2
	VMOVDQU64 (SI)(R8*8), Z3
	VPSUBQ    Z3, Z2, Z2
	VPCMPQ    $0x01, Z0, Z2, K1
	VMOVAPD.Z Z1, K1, Z3
	VPADDQ    Z3, Z2, Z2
	VMOVDQU64 Z2, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    DI, $0x00
	CMOVQLT R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·subLazyToAVX512(SB), NOSPLIT, $0-72
	VXORPD Z0, Z0, Z0
	MOVQ   vOut_len+8(FP), AX
	MOVQ   vOut_base+0(FP), CX
	MOVQ   v0_base+24(FP), DX
	MOVQ   v1_base+48(FP), BX
	MOVQ   AX, SI
	SHRQ   $0x03, SI
	SHLQ   $0x03, SI
	XORQ   DI, DI
	JMP    loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET
