// Code generated by command: go run main.go -vec -out ../../math/vec/asm_ops_amd64.s -stubs ../../math/vec/asm_ops_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func addLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func subToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func subLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func scalarBMulToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func scalarBMulAddToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func scalarBMulSubToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func scalarBMulLazyToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func scalarBMulAddLazyToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func scalarBMulSubLazyToX86(v0 []uint64, c uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulAddToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulSubToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulAddLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func bMulSubLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
