// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

DATA MASK_LO<>+0(SB)/8, $0x00000000ffffffff
GLOBL MASK_LO<>(SB), RODATA|NOPTR, $8

DATA MASK_52<>+0(SB)/8, $0x000fffffffffffff
GLOBL MASK_52<>(SB), RODATA|NOPTR, $8

DATA CVT_52<>+0(SB)/8, $(4503599627370496.0)
GLOBL CVT_52<>(SB), RODATA|NOPTR, $8

// func addToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·addToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Y0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU   (BX)(R8*8), Y1
	VMOVDQU   (SI)(R8*8), Y2
	VPADDQ    Y2, Y1, Y1
	VPSUBQ    Y0, Y1, Y2
	VBLENDVPD Y2, Y1, Y2, Y1
	VMOVDQU   Y1, (DX)(R8*8)
	ADDQ      $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·addWordToAVX2(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y0
	VMOVDQU (BX)(DI*8), Y1
	VPADDQ  Y1, Y0, Y0
	VMOVDQU Y0, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·subToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Y0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU   (BX)(R8*8), Y1
	VMOVDQU   (SI)(R8*8), Y2
	VPSUBQ    Y2, Y1, Y1
	VPADDQ    Y0, Y1, Y2
	VBLENDVPD Y1, Y2, Y1, Y1
	VMOVDQU   Y1, (DX)(R8*8)
	ADDQ      $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·subWordToAVX2(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y0
	VMOVDQU (BX)(DI*8), Y1
	VPSUBQ  Y1, Y0, Y0
	VMOVDQU Y0, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·addToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z1
	VMOVDQU64 (SI)(R8*8), Z2
	VPADDQ    Z2, Z1, Z1
	VPSUBQ    Z0, Z1, Z2
	VPMINUQ   Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512F
TEXT ·addWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPADDQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·subToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z1
	VMOVDQU64 (SI)(R8*8), Z2
	VPSUBQ    Z2, Z1, Z1
	VPADDQ    Z0, Z1, Z2
	VPMINUQ   Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512F
TEXT ·subWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func addScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·addScalarToAVX2(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Y0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Y1
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU   (BX)(R8*8), Y2
	VPADDQ    Y1, Y2, Y2
	VPSUBQ    Y0, Y2, Y3
	VBLENDVPD Y3, Y2, Y3, Y2
	VMOVDQU   Y2, (DX)(R8*8)
	ADDQ      $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	ADDQ    SI, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)
// Requires: AVX, AVX2
TEXT ·addScalarWordToAVX2(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Y0
	MOVQ         AX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y1
	VPADDQ  Y0, Y1, Y1
	VMOVDQU Y1, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	ADDQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·subScalarToAVX2(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Y0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Y1
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU   (BX)(R8*8), Y2
	VPSUBQ    Y1, Y2, Y2
	VPADDQ    Y0, Y2, Y3
	VBLENDVPD Y2, Y3, Y2, Y2
	VMOVDQU   Y2, (DX)(R8*8)
	ADDQ      $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	SUBQ    SI, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)
// Requires: AVX, AVX2
TEXT ·subScalarWordToAVX2(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Y0
	MOVQ         AX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU (DX)(DI*8), Y1
	VPSUBQ  Y0, Y1, Y1
	VMOVDQU Y1, (CX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	SUBQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·addScalarToAVX512(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Z1
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z2
	VPADDQ    Z1, Z2, Z2
	VPSUBQ    Z0, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	ADDQ    SI, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512F
TEXT ·addScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         AX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z1
	VPADDQ    Z0, Z1, Z1
	VMOVDQU64 Z1, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	ADDQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·subScalarToAVX512(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Z1
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z2
	VPSUBQ    Z1, Z2, Z2
	VPADDQ    Z0, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	SUBQ    SI, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512F
TEXT ·subScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         AX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z1
	VPSUBQ    Z0, Z1, Z1
	VMOVDQU64 Z1, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	SUBQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func negToAVX2(vOut []uint64, v []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·negToAVX2(SB), NOSPLIT, $0-56
	VPCMPEQQ     Y0, Y0, Y0
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(DI*8), Y2
	VPSUBQ   Y2, Y1, Y2
	VPCMPEQQ Y2, Y1, Y3
	VPXOR    Y3, Y0, Y3
	VPAND    Y2, Y3, Y2
	VMOVDQU  Y2, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(DI*8), SI
	CMPQ    SI, $0x00
	CMOVQEQ AX, SI
	NEGQ    SI
	ADDQ    AX, SI
	MOVQ    SI, (DX)(DI*8)
	ADDQ    $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func negWordToAVX2(vOut []uint64, v []uint64)
// Requires: AVX, AVX2
TEXT ·negWordToAVX2(SB), NOSPLIT, $0-48
	VXORPD Y0, Y0, Y0
	MOVQ   vOut_len+8(FP), AX
	MOVQ   vOut_base+0(FP), CX
	MOVQ   v_base+24(FP), DX
	MOVQ   AX, BX
	SHRQ   $0x02, BX
	SHLQ   $0x02, BX
	XORQ   SI, SI
	JMP    loop_end

loop_body:
	VMOVDQU (DX)(SI*8), Y1
	VPSUBQ  Y1, Y0, Y1
	VMOVDQU Y1, (CX)(SI*8)
	ADDQ    $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(SI*8), BX
	NEGQ BX
	MOVQ BX, (CX)(SI*8)
	ADDQ $0x01, SI

leftover_loop_end:
	CMPQ SI, AX
	JL   leftover_loop_body
	RET

// func negWordToAVX512(vOut []uint64, v []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·negWordToAVX512(SB), NOSPLIT, $0-48
	VXORPD Z0, Z0, Z0
	MOVQ   vOut_len+8(FP), AX
	MOVQ   vOut_base+0(FP), CX
	MOVQ   v_base+24(FP), DX
	MOVQ   AX, BX
	SHRQ   $0x03, BX
	SHLQ   $0x03, BX
	XORQ   SI, SI
	JMP    loop_end

loop_body:
	VMOVDQU64 (DX)(SI*8), Z1
	VPSUBQ    Z1, Z0, Z1
	VMOVDQU64 Z1, (CX)(SI*8)
	ADDQ      $0x08, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(SI*8), BX
	NEGQ BX
	MOVQ BX, (CX)(SI*8)
	ADDQ $0x01, SI

leftover_loop_end:
	CMPQ SI, AX
	JL   leftover_loop_body
	RET

// func negToAVX512(vOut []uint64, v []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·negToAVX512(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z1, Z0, Z1
	VPCMPQ    $0x04, Z1, Z0, K1
	VMOVAPD.Z Z1, K1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(DI*8), SI
	CMPQ    SI, $0x00
	CMOVQEQ AX, SI
	NEGQ    SI
	ADDQ    AX, SI
	MOVQ    SI, (DX)(DI*8)
	ADDQ    $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)
// Requires: AVX, AVX2
TEXT ·mulScalarWordToAVX2(SB), NOSPLIT, $0-56
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Y1
	VPSHUFD      $0xb1, Y1, Y2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(DI*8), Y3
	VPMULUDQ Y1, Y3, Y4
	VPMULLD  Y2, Y3, Y3
	VPSLLQ   $0x20, Y3, Y5
	VPAND    Y0, Y3, Y3
	VPADDQ   Y5, Y3, Y3
	VPADDQ   Y4, Y3, Y3
	VMOVDQU  Y3, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  SI, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulAddScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)
// Requires: AVX, AVX2
TEXT ·mulAddScalarWordToAVX2(SB), NOSPLIT, $0-56
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Y1
	VPSHUFD      $0xb1, Y1, Y2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(DI*8), Y3
	VPMULUDQ Y1, Y3, Y4
	VPMULLD  Y2, Y3, Y3
	VPSLLQ   $0x20, Y3, Y5
	VPAND    Y0, Y3, Y3
	VPADDQ   Y5, Y3, Y3
	VPADDQ   Y4, Y3, Y3
	VMOVDQU  (DX)(DI*8), Y4
	VPADDQ   Y3, Y4, Y4
	VMOVDQU  Y4, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulSubScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)
// Requires: AVX, AVX2
TEXT ·mulSubScalarWordToAVX2(SB), NOSPLIT, $0-56
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Y1
	VPSHUFD      $0xb1, Y1, Y2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (BX)(DI*8), Y3
	VPMULUDQ Y1, Y3, Y4
	VPMULLD  Y2, Y3, Y3
	VPSLLQ   $0x20, Y3, Y5
	VPAND    Y0, Y3, Y3
	VPADDQ   Y5, Y3, Y3
	VPADDQ   Y4, Y3, Y3
	VMOVDQU  (DX)(DI*8), Y4
	VPSUBQ   Y3, Y4, Y4
	VMOVDQU  Y4, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  SI, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulAddScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulAddScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z2
	VMOVDQU64 (DX)(DI*8), Z1
	VPADDQ    Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulSubScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulSubScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z2
	VMOVDQU64 (DX)(DI*8), Z1
	VPSUBQ    Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulScalarToAVX2(SB), NOSPLIT, $0-80
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X1
	MOVSD        qfInv+72(FP), X2
	VPBROADCASTQ q+56(FP), Y3
	VPBROADCASTQ qf+64(FP), Y4
	VPBROADCASTQ qfInv+72(FP), Y5
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X6
	VPBROADCASTQ c+48(FP), Y7
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(DI*8), Y8
	VORPD        Y0, Y8, Y8
	VSUBPD       Y0, Y8, Y8
	VMULPD       Y8, Y7, Y9
	VFMSUB213PD  Y9, Y7, Y8
	VMULPD       Y9, Y5, Y10
	VROUNDPD     $0x01, Y10, Y10
	VFNMADD231PD Y10, Y4, Y9
	VADDPD       Y9, Y8, Y9
	VADDPD       Y9, Y4, Y9
	VADDPD       Y0, Y9, Y9
	VXORPD       Y0, Y9, Y9
	VPSUBQ       Y3, Y9, Y8
	VBLENDVPD    Y8, Y9, Y8, Y9
	VMOVDQU      Y9, (DX)(DI*8)
	ADDQ         $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X11
	MOVSD        X11, X12
	MULSD        X6, X12
	VFMSUB213SD  X12, X6, X11
	MOVSD        X12, X13
	MULSD        X2, X13
	ROUNDSD      $0x01, X13, X13
	VFNMADD231SD X13, X1, X12
	ADDSD        X11, X12
	ADDSD        X1, X12
	CVTTSD2SQ    X12, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         SI, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulAddScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulAddScalarToAVX2(SB), NOSPLIT, $0-80
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X1
	MOVSD        qfInv+72(FP), X2
	VPBROADCASTQ q+56(FP), Y3
	VPBROADCASTQ qf+64(FP), Y4
	VPBROADCASTQ qfInv+72(FP), Y5
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X6
	VPBROADCASTQ c+48(FP), Y7
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(DI*8), Y8
	VORPD        Y0, Y8, Y8
	VSUBPD       Y0, Y8, Y8
	VMULPD       Y8, Y7, Y9
	VFMSUB213PD  Y9, Y7, Y8
	VMULPD       Y9, Y5, Y10
	VROUNDPD     $0x01, Y10, Y10
	VFNMADD231PD Y10, Y4, Y9
	VADDPD       Y9, Y8, Y9
	VADDPD       Y9, Y4, Y9
	VADDPD       Y0, Y9, Y9
	VXORPD       Y0, Y9, Y9
	VPSUBQ       Y3, Y9, Y8
	VBLENDVPD    Y8, Y9, Y8, Y9
	VMOVDQU      (DX)(DI*8), Y8
	VPADDQ       Y9, Y8, Y8
	VPSUBQ       Y3, Y8, Y9
	VBLENDVPD    Y9, Y8, Y9, Y8
	VMOVDQU      Y8, (DX)(DI*8)
	ADDQ         $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X11
	MOVSD        X11, X12
	MULSD        X6, X12
	VFMSUB213SD  X12, X6, X11
	MOVSD        X12, X13
	MULSD        X2, X13
	ROUNDSD      $0x01, X13, X13
	VFNMADD231SD X13, X1, X12
	ADDSD        X11, X12
	ADDSD        X1, X12
	CVTTSD2SQ    X12, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         (DX)(DI*8), R8
	ADDQ         SI, R8
	MOVQ         R8, SI
	SUBQ         AX, SI
	CMPQ         AX, R8
	CMOVQLS      SI, R8
	MOVQ         R8, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulSubScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulSubScalarToAVX2(SB), NOSPLIT, $0-80
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X1
	MOVSD        qfInv+72(FP), X2
	VPBROADCASTQ q+56(FP), Y3
	VPBROADCASTQ qf+64(FP), Y4
	VPBROADCASTQ qfInv+72(FP), Y5
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X6
	VPBROADCASTQ c+48(FP), Y7
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(DI*8), Y8
	VORPD        Y0, Y8, Y8
	VSUBPD       Y0, Y8, Y8
	VMULPD       Y8, Y7, Y9
	VFMSUB213PD  Y9, Y7, Y8
	VMULPD       Y9, Y5, Y10
	VROUNDPD     $0x01, Y10, Y10
	VFNMADD231PD Y10, Y4, Y9
	VADDPD       Y9, Y8, Y9
	VADDPD       Y9, Y4, Y9
	VADDPD       Y0, Y9, Y9
	VXORPD       Y0, Y9, Y9
	VPSUBQ       Y3, Y9, Y8
	VBLENDVPD    Y8, Y9, Y8, Y9
	VMOVDQU      (DX)(DI*8), Y8
	VPSUBQ       Y9, Y8, Y8
	VPADDQ       Y3, Y8, Y9
	VBLENDVPD    Y8, Y9, Y8, Y8
	VMOVDQU      Y8, (DX)(DI*8)
	ADDQ         $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X11
	MOVSD        X11, X12
	MULSD        X6, X12
	VFMSUB213SD  X12, X6, X11
	MOVSD        X12, X13
	MULSD        X2, X13
	ROUNDSD      $0x01, X13, X13
	VFNMADD231SD X13, X1, X12
	ADDSD        X11, X12
	ADDSD        X1, X12
	CVTTSD2SQ    X12, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         (DX)(DI*8), R8
	SUBQ         SI, R8
	MOVQ         R8, SI
	ADDQ         AX, SI
	CMPQ         AX, R8
	CMOVQLS      SI, R8
	MOVQ         R8, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulScalarToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X0
	MOVSD        qfInv+72(FP), X1
	VPBROADCASTQ q+56(FP), Z2
	VPBROADCASTQ qf+64(FP), Z3
	VPBROADCASTQ qfInv+72(FP), Z4
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X5
	VPBROADCASTQ c+48(FP), Z6
	VCVTUQQ2PD   Z6, Z6
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(DI*8), Z7
	VCVTUQQ2PD   Z7, Z7
	VMULPD       Z7, Z6, Z8
	VFMSUB213PD  Z8, Z6, Z7
	VMULPD       Z8, Z4, Z9
	VRNDSCALEPD  $0x01, Z9, Z9
	VFNMADD231PD Z9, Z3, Z8
	VADDPD       Z8, Z7, Z8
	VADDPD       Z8, Z3, Z8
	VCVTPD2UQQ   Z8, Z8
	VPSUBQ       Z2, Z8, Z7
	VPMINUQ      Z7, Z8, Z8
	VMOVDQU64    Z8, (DX)(DI*8)
	ADDQ         $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X10
	MOVSD        X10, X11
	MULSD        X5, X11
	VFMSUB213SD  X11, X5, X10
	MOVSD        X11, X12
	MULSD        X1, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X0, X11
	ADDSD        X10, X11
	ADDSD        X0, X11
	CVTTSD2SQ    X11, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         SI, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulAddScalarToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X0
	MOVSD        qfInv+72(FP), X1
	VPBROADCASTQ q+56(FP), Z2
	VPBROADCASTQ qf+64(FP), Z3
	VPBROADCASTQ qfInv+72(FP), Z4
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X5
	VPBROADCASTQ c+48(FP), Z6
	VCVTUQQ2PD   Z6, Z6
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(DI*8), Z7
	VCVTUQQ2PD   Z7, Z7
	VMULPD       Z7, Z6, Z8
	VFMSUB213PD  Z8, Z6, Z7
	VMULPD       Z8, Z4, Z9
	VRNDSCALEPD  $0x01, Z9, Z9
	VFNMADD231PD Z9, Z3, Z8
	VADDPD       Z8, Z7, Z8
	VADDPD       Z8, Z3, Z8
	VCVTPD2UQQ   Z8, Z8
	VPSUBQ       Z2, Z8, Z7
	VPMINUQ      Z7, Z8, Z8
	VMOVDQU64    (DX)(DI*8), Z7
	VPADDQ       Z8, Z7, Z7
	VPSUBQ       Z2, Z7, Z8
	VPMINUQ      Z8, Z7, Z7
	VMOVDQU64    Z7, (DX)(DI*8)
	ADDQ         $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X10
	MOVSD        X10, X11
	MULSD        X5, X11
	VFMSUB213SD  X11, X5, X10
	MOVSD        X11, X12
	MULSD        X1, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X0, X11
	ADDSD        X10, X11
	ADDSD        X0, X11
	CVTTSD2SQ    X11, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         (DX)(DI*8), R8
	ADDQ         SI, R8
	MOVQ         R8, SI
	SUBQ         AX, SI
	CMPQ         AX, R8
	CMOVQLS      SI, R8
	MOVQ         R8, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulSubScalarToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+56(FP), AX
	MOVSD        qf+64(FP), X0
	MOVSD        qfInv+72(FP), X1
	VPBROADCASTQ q+56(FP), Z2
	VPBROADCASTQ qf+64(FP), Z3
	VPBROADCASTQ qfInv+72(FP), Z4
	MOVQ         c+48(FP), CX
	CVTSQ2SD     CX, X5
	VPBROADCASTQ c+48(FP), Z6
	VCVTUQQ2PD   Z6, Z6
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(DI*8), Z7
	VCVTUQQ2PD   Z7, Z7
	VMULPD       Z7, Z6, Z8
	VFMSUB213PD  Z8, Z6, Z7
	VMULPD       Z8, Z4, Z9
	VRNDSCALEPD  $0x01, Z9, Z9
	VFNMADD231PD Z9, Z3, Z8
	VADDPD       Z8, Z7, Z8
	VADDPD       Z8, Z3, Z8
	VCVTPD2UQQ   Z8, Z8
	VPSUBQ       Z2, Z8, Z7
	VPMINUQ      Z7, Z8, Z8
	VMOVDQU64    (DX)(DI*8), Z7
	VPSUBQ       Z8, Z7, Z7
	VPADDQ       Z2, Z7, Z8
	VPMINUQ      Z8, Z7, Z7
	VMOVDQU64    Z7, (DX)(DI*8)
	ADDQ         $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(DI*8), SI
	CVTSQ2SD     SI, X10
	MOVSD        X10, X11
	MULSD        X5, X11
	VFMSUB213SD  X11, X5, X10
	MOVSD        X11, X12
	MULSD        X1, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X0, X11
	ADDSD        X10, X11
	ADDSD        X0, X11
	CVTTSD2SQ    X11, SI
	MOVQ         SI, R8
	SUBQ         AX, R8
	CMPQ         AX, SI
	CMOVQLS      R8, SI
	MOVQ         (DX)(DI*8), R8
	SUBQ         SI, R8
	MOVQ         R8, SI
	ADDQ         AX, SI
	CMPQ         AX, R8
	CMOVQLS      SI, R8
	MOVQ         R8, (DX)(DI*8)
	ADDQ         $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func sMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z1, Z6, Z6
	VPMULLQ   Z2, Z5, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 Z5, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulAddScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z1, Z6, Z6
	VPMULLQ   Z2, Z5, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPADDQ    Z5, Z6, Z6
	VPSUBQ    Z1, Z6, Z5
	VPMINUQ   Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulSubScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z1, Z6, Z6
	VPMULLQ   Z2, Z5, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPSUBQ    Z5, Z6, Z6
	VPADDQ    Z1, Z6, Z5
	VPMINUQ   Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z4, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z3, Z5, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   Z6, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulAddScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z4, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z3, Z5, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPADDQ      Z6, Z5, Z5
	VPSUBQ      Z2, Z5, Z8
	VPMINUQ     Z8, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulSubScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z4, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z3, Z5, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPSUBQ      Z6, Z5, Z5
	VPADDQ      Z2, Z5, Z8
	VPMINUQ     Z8, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func mulWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·mulWordToAVX2(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	MOVQ         AX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (DX)(DI*8), Y1
	VMOVDQU  (BX)(DI*8), Y2
	VPSHUFD  $0xb1, Y2, Y3
	VPMULUDQ Y2, Y1, Y2
	VPMULLD  Y3, Y1, Y1
	VPSLLQ   $0x20, Y1, Y3
	VPAND    Y0, Y1, Y1
	VPADDQ   Y3, Y1, Y1
	VPADDQ   Y2, Y1, Y1
	VMOVDQU  Y1, (CX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  SI, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulAddWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·mulAddWordToAVX2(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	MOVQ         AX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (DX)(DI*8), Y1
	VMOVDQU  (BX)(DI*8), Y2
	VPSHUFD  $0xb1, Y2, Y3
	VPMULUDQ Y2, Y1, Y2
	VPMULLD  Y3, Y1, Y1
	VPSLLQ   $0x20, Y1, Y3
	VPAND    Y0, Y1, Y1
	VPADDQ   Y3, Y1, Y1
	VPADDQ   Y2, Y1, Y1
	VMOVDQU  (CX)(DI*8), Y2
	VPADDQ   Y1, Y2, Y2
	VMOVDQU  Y2, (CX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulSubWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX, AVX2
TEXT ·mulSubWordToAVX2(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Y0
	VPSLLQ       $0x20, Y0, Y0
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	MOVQ         AX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU  (DX)(DI*8), Y1
	VMOVDQU  (BX)(DI*8), Y2
	VPSHUFD  $0xb1, Y2, Y3
	VPMULUDQ Y2, Y1, Y2
	VPMULLD  Y3, Y1, Y1
	VPSLLQ   $0x20, Y1, Y3
	VPAND    Y0, Y1, Y1
	VPADDQ   Y3, Y1, Y1
	VPADDQ   Y2, Y1, Y1
	VMOVDQU  (CX)(DI*8), Y2
	VPSUBQ   Y1, Y2, Y2
	VMOVDQU  Y2, (CX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  SI, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulAddWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulAddWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z1
	VMOVDQU64 (CX)(DI*8), Z0
	VPADDQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulSubWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulSubWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z1
	VMOVDQU64 (CX)(DI*8), Z0
	VPSUBQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulToAVX2(SB), NOSPLIT, $0-96
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X1
	MOVSD        qfInv+88(FP), X2
	VPBROADCASTQ q+72(FP), Y3
	VPBROADCASTQ qf+80(FP), Y4
	VPBROADCASTQ qfInv+88(FP), Y5
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(R8*8), Y6
	VMOVDQU      (SI)(R8*8), Y7
	VORPD        Y0, Y6, Y6
	VSUBPD       Y0, Y6, Y6
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	VMULPD       Y6, Y7, Y8
	VFMSUB213PD  Y8, Y7, Y6
	VMULPD       Y8, Y5, Y7
	VROUNDPD     $0x01, Y7, Y7
	VFNMADD231PD Y7, Y4, Y8
	VADDPD       Y8, Y6, Y8
	VADDPD       Y8, Y4, Y8
	VADDPD       Y0, Y8, Y8
	VXORPD       Y0, Y8, Y8
	VPSUBQ       Y3, Y8, Y6
	VBLENDVPD    Y6, Y8, Y6, Y8
	VMOVDQU      Y8, (DX)(R8*8)
	ADDQ         $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X9
	CVTSQ2SD     R9, X10
	MOVSD        X9, X11
	MULSD        X10, X11
	VFMSUB213SD  X11, X10, X9
	MOVSD        X11, X12
	MULSD        X2, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X1, X11
	ADDSD        X9, X11
	ADDSD        X1, X11
	CVTTSD2SQ    X11, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         DI, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func mulAddToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulAddToAVX2(SB), NOSPLIT, $0-96
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X1
	MOVSD        qfInv+88(FP), X2
	VPBROADCASTQ q+72(FP), Y3
	VPBROADCASTQ qf+80(FP), Y4
	VPBROADCASTQ qfInv+88(FP), Y5
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(R8*8), Y6
	VMOVDQU      (SI)(R8*8), Y7
	VORPD        Y0, Y6, Y6
	VSUBPD       Y0, Y6, Y6
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	VMULPD       Y6, Y7, Y8
	VFMSUB213PD  Y8, Y7, Y6
	VMULPD       Y8, Y5, Y7
	VROUNDPD     $0x01, Y7, Y7
	VFNMADD231PD Y7, Y4, Y8
	VADDPD       Y8, Y6, Y8
	VADDPD       Y8, Y4, Y8
	VADDPD       Y0, Y8, Y8
	VXORPD       Y0, Y8, Y8
	VPSUBQ       Y3, Y8, Y6
	VBLENDVPD    Y6, Y8, Y6, Y8
	VMOVDQU      (DX)(R8*8), Y6
	VPADDQ       Y8, Y6, Y6
	VPSUBQ       Y3, Y6, Y7
	VBLENDVPD    Y7, Y6, Y7, Y6
	VMOVDQU      Y6, (DX)(R8*8)
	ADDQ         $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X9
	CVTSQ2SD     R9, X10
	MOVSD        X9, X11
	MULSD        X10, X11
	VFMSUB213SD  X11, X10, X9
	MOVSD        X11, X12
	MULSD        X2, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X1, X11
	ADDSD        X9, X11
	ADDSD        X1, X11
	CVTTSD2SQ    X11, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         (DX)(R8*8), R9
	ADDQ         DI, R9
	MOVQ         R9, DI
	SUBQ         AX, DI
	CMPQ         AX, R9
	CMOVQLS      DI, R9
	MOVQ         R9, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func mulSubToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX, AVX2, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulSubToAVX2(SB), NOSPLIT, $0-96
	VPBROADCASTQ CVT_52<>+0(SB), Y0
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X1
	MOVSD        qfInv+88(FP), X2
	VPBROADCASTQ q+72(FP), Y3
	VPBROADCASTQ qf+80(FP), Y4
	VPBROADCASTQ qfInv+88(FP), Y5
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU      (BX)(R8*8), Y6
	VMOVDQU      (SI)(R8*8), Y7
	VORPD        Y0, Y6, Y6
	VSUBPD       Y0, Y6, Y6
	VORPD        Y0, Y7, Y7
	VSUBPD       Y0, Y7, Y7
	VMULPD       Y6, Y7, Y8
	VFMSUB213PD  Y8, Y7, Y6
	VMULPD       Y8, Y5, Y7
	VROUNDPD     $0x01, Y7, Y7
	VFNMADD231PD Y7, Y4, Y8
	VADDPD       Y8, Y6, Y8
	VADDPD       Y8, Y4, Y8
	VADDPD       Y0, Y8, Y8
	VXORPD       Y0, Y8, Y8
	VPSUBQ       Y3, Y8, Y6
	VBLENDVPD    Y6, Y8, Y6, Y8
	VMOVDQU      (DX)(R8*8), Y6
	VPSUBQ       Y8, Y6, Y6
	VPADDQ       Y3, Y6, Y7
	VBLENDVPD    Y6, Y7, Y6, Y6
	VMOVDQU      Y6, (DX)(R8*8)
	ADDQ         $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X9
	CVTSQ2SD     R9, X10
	MOVSD        X9, X11
	MULSD        X10, X11
	VFMSUB213SD  X11, X10, X9
	MOVSD        X11, X12
	MULSD        X2, X12
	ROUNDSD      $0x01, X12, X12
	VFNMADD231SD X12, X1, X11
	ADDSD        X9, X11
	ADDSD        X1, X11
	CVTTSD2SQ    X11, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         (DX)(R8*8), R9
	SUBQ         DI, R9
	MOVQ         R9, DI
	ADDQ         AX, DI
	CMPQ         AX, R9
	CMOVQLS      DI, R9
	MOVQ         R9, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func mulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulToAVX512(SB), NOSPLIT, $0-96
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X0
	MOVSD        qfInv+88(FP), X1
	VPBROADCASTQ q+72(FP), Z2
	VPBROADCASTQ qf+80(FP), Z3
	VPBROADCASTQ qfInv+88(FP), Z4
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(R8*8), Z5
	VMOVDQU64    (SI)(R8*8), Z6
	VCVTUQQ2PD   Z5, Z5
	VCVTUQQ2PD   Z6, Z6
	VMULPD       Z5, Z6, Z7
	VFMSUB213PD  Z7, Z6, Z5
	VMULPD       Z7, Z4, Z6
	VRNDSCALEPD  $0x01, Z6, Z6
	VFNMADD231PD Z6, Z3, Z7
	VADDPD       Z7, Z5, Z7
	VADDPD       Z7, Z3, Z7
	VCVTPD2UQQ   Z7, Z7
	VPSUBQ       Z2, Z7, Z5
	VPMINUQ      Z5, Z7, Z7
	VMOVDQU64    Z7, (DX)(R8*8)
	ADDQ         $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X8
	CVTSQ2SD     R9, X9
	MOVSD        X8, X10
	MULSD        X9, X10
	VFMSUB213SD  X10, X9, X8
	MOVSD        X10, X11
	MULSD        X1, X11
	ROUNDSD      $0x01, X11, X11
	VFNMADD231SD X11, X0, X10
	ADDSD        X8, X10
	ADDSD        X0, X10
	CVTTSD2SQ    X10, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         DI, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func mulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulAddToAVX512(SB), NOSPLIT, $0-96
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X0
	MOVSD        qfInv+88(FP), X1
	VPBROADCASTQ q+72(FP), Z2
	VPBROADCASTQ qf+80(FP), Z3
	VPBROADCASTQ qfInv+88(FP), Z4
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(R8*8), Z5
	VMOVDQU64    (SI)(R8*8), Z6
	VCVTUQQ2PD   Z5, Z5
	VCVTUQQ2PD   Z6, Z6
	VMULPD       Z5, Z6, Z7
	VFMSUB213PD  Z7, Z6, Z5
	VMULPD       Z7, Z4, Z6
	VRNDSCALEPD  $0x01, Z6, Z6
	VFNMADD231PD Z6, Z3, Z7
	VADDPD       Z7, Z5, Z7
	VADDPD       Z7, Z3, Z7
	VCVTPD2UQQ   Z7, Z7
	VPSUBQ       Z2, Z7, Z5
	VPMINUQ      Z5, Z7, Z7
	VMOVDQU64    (DX)(R8*8), Z5
	VPADDQ       Z7, Z5, Z5
	VPSUBQ       Z2, Z5, Z6
	VPMINUQ      Z6, Z5, Z5
	VMOVDQU64    Z5, (DX)(R8*8)
	ADDQ         $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X8
	CVTSQ2SD     R9, X9
	MOVSD        X8, X10
	MULSD        X9, X10
	VFMSUB213SD  X10, X9, X8
	MOVSD        X10, X11
	MULSD        X1, X11
	ROUNDSD      $0x01, X11, X11
	VFNMADD231SD X11, X0, X10
	ADDSD        X8, X10
	ADDSD        X0, X10
	CVTTSD2SQ    X10, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         (DX)(R8*8), R9
	ADDQ         DI, R9
	MOVQ         R9, DI
	SUBQ         AX, DI
	CMPQ         AX, R9
	CMOVQLS      DI, R9
	MOVQ         R9, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func mulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F, CMOV, FMA3, SSE2, SSE4.1
TEXT ·mulSubToAVX512(SB), NOSPLIT, $0-96
	MOVQ         q+72(FP), AX
	MOVSD        qf+80(FP), X0
	MOVSD        qfInv+88(FP), X1
	VPBROADCASTQ q+72(FP), Z2
	VPBROADCASTQ qf+80(FP), Z3
	VPBROADCASTQ qfInv+88(FP), Z4
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64    (BX)(R8*8), Z5
	VMOVDQU64    (SI)(R8*8), Z6
	VCVTUQQ2PD   Z5, Z5
	VCVTUQQ2PD   Z6, Z6
	VMULPD       Z5, Z6, Z7
	VFMSUB213PD  Z7, Z6, Z5
	VMULPD       Z7, Z4, Z6
	VRNDSCALEPD  $0x01, Z6, Z6
	VFNMADD231PD Z6, Z3, Z7
	VADDPD       Z7, Z5, Z7
	VADDPD       Z7, Z3, Z7
	VCVTPD2UQQ   Z7, Z7
	VPSUBQ       Z2, Z7, Z5
	VPMINUQ      Z5, Z7, Z7
	VMOVDQU64    (DX)(R8*8), Z5
	VPSUBQ       Z7, Z5, Z5
	VPADDQ       Z2, Z5, Z6
	VPMINUQ      Z6, Z5, Z5
	VMOVDQU64    Z5, (DX)(R8*8)
	ADDQ         $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ         (BX)(R8*8), DI
	MOVQ         (SI)(R8*8), R9
	CVTSQ2SD     DI, X8
	CVTSQ2SD     R9, X9
	MOVSD        X8, X10
	MULSD        X9, X10
	VFMSUB213SD  X10, X9, X8
	MOVSD        X10, X11
	MULSD        X1, X11
	ROUNDSD      $0x01, X11, X11
	VFNMADD231SD X11, X0, X10
	ADDSD        X8, X10
	ADDSD        X0, X10
	CVTTSD2SQ    X10, DI
	MOVQ         DI, R9
	SUBQ         AX, R9
	CMPQ         AX, DI
	CMOVQLS      R9, DI
	MOVQ         (DX)(R8*8), R9
	SUBQ         DI, R9
	MOVQ         R9, DI
	ADDQ         AX, DI
	CMPQ         AX, R9
	CMOVQLS      DI, R9
	MOVQ         R9, (DX)(R8*8)
	ADDQ         $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func sMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z1, Z5, Z5
	VPMULLQ   Z3, Z2, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulAddToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z1, Z5, Z5
	VPMULLQ   Z3, Z2, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPADDQ    Z2, Z3, Z3
	VPSUBQ    Z1, Z3, Z2
	VPMINUQ   Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulSubToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z1, Z5, Z5
	VPMULLQ   Z3, Z2, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPSUBQ    Z2, Z3, Z3
	VPADDQ    Z1, Z3, Z2
	VPMINUQ   Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z3, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   Z6, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulAddToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z3, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPADDQ      Z6, Z3, Z3
	VPSUBQ      Z2, Z3, Z4
	VPMINUQ     Z4, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulSubToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z3, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPSUBQ      Z6, Z3, Z3
	VPADDQ      Z2, Z3, Z4
	VPMINUQ     Z4, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func reduceToAVX512(vOut []uint64, v []uint64, q uint64, div uint64, logQ uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·reduceToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Z1
	MOVQ         div+56(FP), CX
	MOVQ         logQ+64(FP), BX
	VPBROADCASTQ div+56(FP), Z2
	VPBROADCASTQ logQ+64(FP), Z3
	VPSRLQ       $0x20, Z2, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLVQ   Z3, Z5, Z6
	VPSRLQ    $0x20, Z6, Z7
	VPMULUDQ  Z2, Z6, Z8
	VPMULUDQ  Z4, Z6, Z6
	VPMULUDQ  Z2, Z7, Z9
	VPMULUDQ  Z4, Z7, Z7
	VPSRLQ    $0x20, Z8, Z8
	VPADDQ    Z8, Z6, Z6
	VPANDQ    Z0, Z6, Z8
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z7, Z6, Z7
	VPADDQ    Z8, Z9, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z7, Z6, Z7
	VPMULLQ   Z7, Z1, Z7
	VPSUBQ    Z7, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 Z5, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	SHRXQ   BX, R10, R11
	MOVQ    CX, DX
	MULXQ   R11, DX, R11
	IMULQ   AX, R11
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func reduce2QToAVX2(vOut []uint64, v []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·reduce2QToAVX2(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x02, SI
	SHLQ         $0x02, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU   (BX)(DI*8), Y1
	VPSUBQ    Y0, Y1, Y2
	VBLENDVPD Y2, Y1, Y2, Y1
	VMOVDQU   Y1, (DX)(DI*8)
	ADDQ      $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(DI*8), SI
	MOVQ    SI, R8
	SUBQ    AX, R8
	CMPQ    AX, SI
	CMOVQLS R8, SI
	MOVQ    SI, (DX)(DI*8)
	ADDQ    $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func reduce2QToAVX512(vOut []uint64, v []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·reduce2QToAVX512(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z0, Z1, Z2
	VPMINUQ   Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(DI*8), SI
	MOVQ    SI, R8
	SUBQ    AX, R8
	CMPQ    AX, SI
	CMOVQLS R8, SI
	MOVQ    SI, (DX)(DI*8)
	ADDQ    $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func reduce4QToAVX2(vOut []uint64, v []uint64, q uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·reduce4QToAVX2(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	MOVQ         AX, CX
	ADDQ         AX, CX
	VPADDQ       Y0, Y0, Y1
	MOVQ         vOut_len+8(FP), DX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v_base+24(FP), SI
	MOVQ         DX, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU   (SI)(R8*8), Y2
	VPSUBQ    Y1, Y2, Y3
	VBLENDVPD Y3, Y2, Y3, Y2
	VPSUBQ    Y0, Y2, Y3
	VBLENDVPD Y3, Y2, Y3, Y2
	VMOVDQU   Y2, (BX)(R8*8)
	ADDQ      $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R8*8), DI
	MOVQ    DI, R9
	SUBQ    CX, R9
	CMPQ    CX, DI
	CMOVQLS R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, DX
	JL   leftover_loop_body
	RET

// func reduce4QToAVX512(vOut []uint64, v []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·reduce4QToAVX512(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Z0
	MOVQ         AX, CX
	ADDQ         AX, CX
	VPADDQ       Z0, Z0, Z1
	MOVQ         vOut_len+8(FP), DX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v_base+24(FP), SI
	MOVQ         DX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R8*8), Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VPSUBQ    Z0, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (BX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R8*8), DI
	MOVQ    DI, R9
	SUBQ    CX, R9
	CMPQ    CX, DI
	CMOVQLS R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, DX
	JL   leftover_loop_body
	RET
