// Code generated by command: go run main.go -vec -out ../../math/vec/asm_ops_amd64.s -stubs ../../math/vec/asm_ops_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func addToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)
// Requires: AVX, AVX2, AVX512F, AVX512VL, CMOV
TEXT ·addToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	MOVQ         v0_base+0(FP), CX
	MOVQ         v1_base+24(FP), DX
	MOVQ         vOut_base+56(FP), BX
	MOVQ         vOut_len+64(FP), SI
	MOVQ         SI, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (CX)(R8*8), Y1
	VMOVDQU  (DX)(R8*8), Y2
	VPADDQ   Y2, Y1, Y1
	VPCMPGTQ Y0, Y1, Y2
	VPCMPEQQ Y1, Y0, Y3
	VPORQ    Y2, Y3, Y2
	VPANDQ   Y0, Y2, Y2
	VPSUBQ   Y2, Y1, Y1
	VMOVDQU  Y1, (BX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (CX)(R8*8), DI
	MOVQ    (DX)(R8*8), R9
	ADDQ    R9, DI
	XORQ    R9, R9
	CMPQ    DI, AX
	CMOVQGE AX, R9
	SUBQ    R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, SI
	JL   leftover_loop_body
	RET

// func addLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·addLazyToAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPADDQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func subToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)
// Requires: AVX, AVX2, AVX512F, AVX512VL, CMOV
TEXT ·subToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	MOVQ         v0_base+0(FP), CX
	MOVQ         v1_base+24(FP), DX
	MOVQ         vOut_base+56(FP), BX
	MOVQ         vOut_len+64(FP), SI
	MOVQ         SI, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	VPXOR        Y1, Y1, Y1
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (CX)(R8*8), Y2
	VMOVDQU  (DX)(R8*8), Y3
	VPSUBQ   Y3, Y2, Y2
	VPCMPGTQ Y2, Y1, Y3
	VPANDQ   Y0, Y3, Y3
	VPADDQ   Y3, Y2, Y2
	VMOVDQU  Y2, (BX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (CX)(R8*8), DI
	MOVQ    (DX)(R8*8), R9
	SUBQ    R9, DI
	XORQ    R9, R9
	CMPQ    DI, $0x00
	CMOVQLT AX, R9
	ADDQ    R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, SI
	JL   leftover_loop_body
	RET

// func subLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·subLazyToAVX2(SB), NOSPLIT, $0-72
	MOVQ  v0_base+0(FP), AX
	MOVQ  v1_base+24(FP), CX
	MOVQ  vOut_base+48(FP), DX
	MOVQ  vOut_len+56(FP), BX
	MOVQ  BX, SI
	SHRQ  $0x02, SI
	SHLQ  $0x02, SI
	VPXOR Y0, Y0, Y0
	XORQ  DI, DI
	JMP   loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPSUBQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET
