// Code generated by command: go run main.go -vec -out ../../math/vec/asm_ops_amd64.s -stubs ../../math/vec/asm_ops_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

DATA ONE<>+0(SB)/8, $0x0000000000000001
GLOBL ONE<>(SB), RODATA|NOPTR, $8

// func addToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·addToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	VPBROADCASTQ ONE<>+0(SB), Y1
	VPSUBQ       Y1, Y0, Y1
	MOVQ         v0_base+0(FP), CX
	MOVQ         v1_base+24(FP), DX
	MOVQ         vOut_base+56(FP), BX
	MOVQ         vOut_len+64(FP), SI
	MOVQ         SI, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (CX)(R8*8), Y2
	VMOVDQU  (DX)(R8*8), Y3
	VPADDQ   Y3, Y2, Y2
	VPCMPGTQ Y1, Y2, Y3
	VPAND    Y0, Y3, Y3
	VPSUBQ   Y3, Y2, Y2
	VMOVDQU  Y2, (BX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (CX)(R8*8), DI
	MOVQ    (DX)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    DI, AX
	CMOVQGE R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, SI
	JL   leftover_loop_body
	RET

// func addLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·addLazyToAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPADDQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func subToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)
// Requires: AVX, AVX2, CMOV
TEXT ·subToAVX2(SB), NOSPLIT, $0-80
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Y0
	MOVQ         v0_base+0(FP), CX
	MOVQ         v1_base+24(FP), DX
	MOVQ         vOut_base+56(FP), BX
	MOVQ         vOut_len+64(FP), SI
	MOVQ         SI, DI
	SHRQ         $0x02, DI
	SHLQ         $0x02, DI
	VPXOR        Y1, Y1, Y1
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU  (CX)(R8*8), Y2
	VMOVDQU  (DX)(R8*8), Y3
	VPSUBQ   Y3, Y2, Y2
	VPCMPGTQ Y2, Y1, Y3
	VPAND    Y0, Y3, Y3
	VPADDQ   Y3, Y2, Y2
	VMOVDQU  Y2, (BX)(R8*8)
	ADDQ     $0x04, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (CX)(R8*8), DI
	MOVQ    (DX)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    DI, $0x00
	CMOVQLT R9, DI
	MOVQ    DI, (BX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, SI
	JL   leftover_loop_body
	RET

// func subLazyToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·subLazyToAVX2(SB), NOSPLIT, $0-72
	MOVQ  v0_base+0(FP), AX
	MOVQ  v1_base+24(FP), CX
	MOVQ  vOut_base+48(FP), DX
	MOVQ  vOut_len+56(FP), BX
	MOVQ  BX, SI
	SHRQ  $0x02, SI
	SHLQ  $0x02, SI
	VPXOR Y0, Y0, Y0
	XORQ  DI, DI
	JMP   loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPSUBQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func bMulToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
// Requires: CMOV
TEXT ·bMulToX86(SB), NOSPLIT, $0-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ    (DI)(R11*8), AX
	MOVQ    (R8)(R11*8), DX
	MULQ    DX
	MOVQ    DX, R12
	MOVQ    AX, R13
	MOVQ    R12, R14
	IMULQ   BX, R14
	MOVQ    R13, AX
	MULQ    BX
	ADDQ    DX, R14
	MOVQ    AX, R15
	MOVQ    R12, AX
	MULQ    SI
	ADDQ    DX, R14
	MOVQ    AX, R12
	MOVQ    R13, AX
	MULQ    SI
	ADDQ    R15, DX
	ADCQ    $0x00, R14
	ADDQ    R12, DX
	ADCQ    $0x00, R14
	IMULQ   CX, R14
	MOVQ    R13, AX
	SUBQ    R14, AX
	MOVQ    AX, DX
	SUBQ    CX, DX
	CMPQ    AX, CX
	CMOVQGE DX, AX
	MOVQ    AX, (R9)(R11*8)
	ADDQ    $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func bMulAddToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
// Requires: CMOV
TEXT ·bMulAddToX86(SB), NOSPLIT, $8-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ    (DI)(R11*8), AX
	MOVQ    (R8)(R11*8), DX
	MOVQ    (R9)(R11*8), R12
	MULQ    DX
	MOVQ    DX, R13
	MOVQ    AX, R14
	MOVQ    R13, R15
	IMULQ   BX, R15
	MOVQ    R14, AX
	MULQ    BX
	ADDQ    DX, R15
	MOVQ    AX, BP
	MOVQ    R13, AX
	MULQ    SI
	ADDQ    DX, R15
	MOVQ    AX, R13
	MOVQ    R14, AX
	MULQ    SI
	ADDQ    BP, DX
	ADCQ    $0x00, R15
	ADDQ    R13, DX
	ADCQ    $0x00, R15
	IMULQ   CX, R15
	MOVQ    R14, AX
	SUBQ    R15, AX
	MOVQ    AX, DX
	SUBQ    CX, DX
	CMPQ    AX, CX
	CMOVQGE DX, AX
	ADDQ    AX, R12
	MOVQ    R12, AX
	SUBQ    CX, AX
	CMPQ    R12, CX
	CMOVQGE AX, R12
	MOVQ    R12, (R9)(R11*8)
	ADDQ    $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func bMulSubToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
// Requires: CMOV
TEXT ·bMulSubToX86(SB), NOSPLIT, $8-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ    (DI)(R11*8), AX
	MOVQ    (R8)(R11*8), DX
	MOVQ    (R9)(R11*8), R12
	MULQ    DX
	MOVQ    DX, R13
	MOVQ    AX, R14
	MOVQ    R13, R15
	IMULQ   BX, R15
	MOVQ    R14, AX
	MULQ    BX
	ADDQ    DX, R15
	MOVQ    AX, BP
	MOVQ    R13, AX
	MULQ    SI
	ADDQ    DX, R15
	MOVQ    AX, R13
	MOVQ    R14, AX
	MULQ    SI
	ADDQ    BP, DX
	ADCQ    $0x00, R15
	ADDQ    R13, DX
	ADCQ    $0x00, R15
	IMULQ   CX, R15
	MOVQ    R14, AX
	SUBQ    R15, AX
	MOVQ    AX, DX
	SUBQ    CX, DX
	CMPQ    AX, CX
	CMOVQGE DX, AX
	SUBQ    AX, R12
	MOVQ    R12, AX
	ADDQ    CX, AX
	CMPQ    R12, $0x00
	CMOVQLT AX, R12
	MOVQ    R12, (R9)(R11*8)
	ADDQ    $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func bMulLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
TEXT ·bMulLazyToX86(SB), NOSPLIT, $0-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ  (DI)(R11*8), AX
	MOVQ  (R8)(R11*8), DX
	MULQ  DX
	MOVQ  DX, R12
	MOVQ  AX, R13
	MOVQ  R12, R14
	IMULQ BX, R14
	MOVQ  R13, AX
	MULQ  BX
	ADDQ  DX, R14
	MOVQ  AX, R15
	MOVQ  R12, AX
	MULQ  SI
	ADDQ  DX, R14
	MOVQ  AX, R12
	MOVQ  R13, AX
	MULQ  SI
	ADDQ  R15, DX
	ADCQ  $0x00, R14
	ADDQ  R12, DX
	ADCQ  $0x00, R14
	IMULQ CX, R14
	MOVQ  R13, AX
	SUBQ  R14, AX
	MOVQ  AX, (R9)(R11*8)
	ADDQ  $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func bMulAddLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
TEXT ·bMulAddLazyToX86(SB), NOSPLIT, $8-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ  (DI)(R11*8), AX
	MOVQ  (R8)(R11*8), DX
	MOVQ  (R9)(R11*8), R12
	MULQ  DX
	MOVQ  DX, R13
	MOVQ  AX, R14
	MOVQ  R13, R15
	IMULQ BX, R15
	MOVQ  R14, AX
	MULQ  BX
	ADDQ  DX, R15
	MOVQ  AX, BP
	MOVQ  R13, AX
	MULQ  SI
	ADDQ  DX, R15
	MOVQ  AX, R13
	MOVQ  R14, AX
	MULQ  SI
	ADDQ  BP, DX
	ADCQ  $0x00, R15
	ADDQ  R13, DX
	ADCQ  $0x00, R15
	IMULQ CX, R15
	MOVQ  R14, AX
	SUBQ  R15, AX
	ADDQ  AX, R12
	MOVQ  R12, (R9)(R11*8)
	ADDQ  $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func bMulSubLazyToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
TEXT ·bMulSubLazyToX86(SB), NOSPLIT, $8-96
	MOVQ q+48(FP), CX
	MOVQ divHi+56(FP), BX
	MOVQ divLo+64(FP), SI
	MOVQ v0_base+0(FP), DI
	MOVQ v1_base+24(FP), R8
	MOVQ vOut_base+72(FP), R9
	MOVQ vOut_len+80(FP), R10
	XORQ R11, R11
	JMP  loop_end

loop_body:
	MOVQ  (DI)(R11*8), AX
	MOVQ  (R8)(R11*8), DX
	MOVQ  (R9)(R11*8), R12
	MULQ  DX
	MOVQ  DX, R13
	MOVQ  AX, R14
	MOVQ  R13, R15
	IMULQ BX, R15
	MOVQ  R14, AX
	MULQ  BX
	ADDQ  DX, R15
	MOVQ  AX, BP
	MOVQ  R13, AX
	MULQ  SI
	ADDQ  DX, R15
	MOVQ  AX, R13
	MOVQ  R14, AX
	MULQ  SI
	ADDQ  BP, DX
	ADCQ  $0x00, R15
	ADDQ  R13, DX
	ADCQ  $0x00, R15
	IMULQ CX, R15
	MOVQ  R14, AX
	SUBQ  R15, AX
	MOVQ  CX, DX
	ADDQ  CX, DX
	SUBQ  AX, DX
	ADDQ  DX, R12
	MOVQ  R12, (R9)(R11*8)
	ADDQ  $0x01, R11

loop_end:
	CMPQ R11, R10
	JL   loop_body
	RET

// func mMulToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
// Requires: CMOV
TEXT ·mMulToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ    (SI)(R10*8), AX
	MOVQ    (DI)(R10*8), DX
	MULQ    DX
	MOVQ    DX, R11
	IMULQ   BX, AX
	MULQ    CX
	SUBQ    DX, R11
	ADDQ    CX, R11
	MOVQ    R11, AX
	SUBQ    CX, AX
	CMPQ    R11, CX
	CMOVQGE AX, R11
	MOVQ    R11, (R8)(R10*8)
	ADDQ    $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET

// func mMulAddToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
// Requires: CMOV
TEXT ·mMulAddToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ    (SI)(R10*8), AX
	MOVQ    (DI)(R10*8), DX
	MOVQ    (R8)(R10*8), R11
	MULQ    DX
	MOVQ    DX, R12
	IMULQ   BX, AX
	MULQ    CX
	SUBQ    DX, R12
	ADDQ    CX, R12
	MOVQ    R12, AX
	SUBQ    CX, AX
	CMPQ    R12, CX
	CMOVQGE AX, R12
	ADDQ    R12, R11
	MOVQ    R11, AX
	SUBQ    CX, AX
	CMPQ    R11, CX
	CMOVQGE AX, R11
	MOVQ    R11, (R8)(R10*8)
	ADDQ    $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET

// func mMulSubToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
// Requires: CMOV
TEXT ·mMulSubToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ    (SI)(R10*8), AX
	MOVQ    (DI)(R10*8), DX
	MOVQ    (R8)(R10*8), R11
	MULQ    DX
	MOVQ    DX, R12
	IMULQ   BX, AX
	MULQ    CX
	SUBQ    DX, R12
	ADDQ    CX, R12
	MOVQ    R12, AX
	SUBQ    CX, AX
	CMPQ    R12, CX
	CMOVQGE AX, R12
	SUBQ    R12, R11
	MOVQ    R11, AX
	ADDQ    CX, AX
	CMPQ    R11, $0x00
	CMOVQLT AX, R11
	MOVQ    R11, (R8)(R10*8)
	ADDQ    $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET

// func mMulLazyToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
TEXT ·mMulLazyToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ  (SI)(R10*8), AX
	MOVQ  (DI)(R10*8), DX
	MULQ  DX
	MOVQ  DX, R11
	IMULQ BX, AX
	MULQ  CX
	SUBQ  DX, R11
	ADDQ  CX, R11
	MOVQ  R11, (R8)(R10*8)
	ADDQ  $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET

// func mMulAddLazyToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
TEXT ·mMulAddLazyToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ  (SI)(R10*8), AX
	MOVQ  (DI)(R10*8), DX
	MOVQ  (R8)(R10*8), R11
	MULQ  DX
	MOVQ  DX, R12
	IMULQ BX, AX
	MULQ  CX
	SUBQ  DX, R12
	ADDQ  CX, R12
	ADDQ  R12, R11
	MOVQ  R11, (R8)(R10*8)
	ADDQ  $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET

// func mMulSubLazyToX86(v0 []uint64, v1 []uint64, q uint64, inv uint64, vOut []uint64)
TEXT ·mMulSubLazyToX86(SB), NOSPLIT, $0-88
	MOVQ q+48(FP), CX
	MOVQ inv+56(FP), BX
	MOVQ v0_base+0(FP), SI
	MOVQ v1_base+24(FP), DI
	MOVQ vOut_base+64(FP), R8
	MOVQ vOut_len+72(FP), R9
	XORQ R10, R10
	JMP  loop_end

loop_body:
	MOVQ  (SI)(R10*8), AX
	MOVQ  (DI)(R10*8), DX
	MOVQ  (R8)(R10*8), R11
	MULQ  DX
	MOVQ  DX, R12
	IMULQ BX, AX
	MULQ  CX
	SUBQ  DX, R12
	ADDQ  CX, R12
	MOVQ  CX, AX
	ADDQ  CX, AX
	SUBQ  R12, AX
	ADDQ  AX, R11
	MOVQ  R11, (R8)(R10*8)
	ADDQ  $0x01, R10

loop_end:
	CMPQ R10, R9
	JL   loop_body
	RET
