// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func negToAVX2(vOut []uint64, v []uint64, q uint64)

//go:noescape
func negWordToAVX2(vOut []uint64, v []uint64)

//go:noescape
func negToAVX512(vOut []uint64, v []uint64, q uint64)

//go:noescape
func negWordToAVX512(vOut []uint64, v []uint64)

//go:noescape
func mFormToAVX512(vOut []uint64, v []uint64, q uint64, divHi uint64, divLo uint64)

//go:noescape
func invMFormToAVX512(vOut []uint64, v []uint64, q uint64, inv uint64)

//go:noescape
func mulScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulAddScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulSubScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulAddScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulSubScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func mMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func mMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func mMulScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func mMulAddScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func mMulSubScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, inv uint64)

//go:noescape
func sMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func mulWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func mMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func mMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func mMulLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func mMulAddLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func mMulSubLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, inv uint64)

//go:noescape
func sMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func reduceToAVX512(vOut []uint64, v []uint64, q uint64, divHi uint64)
