// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func negToAVX2(vOut []uint64, v []uint64, q uint64)

//go:noescape
func negWordToAVX2(vOut []uint64, v []uint64)

//go:noescape
func negWordToAVX512(vOut []uint64, v []uint64)

//go:noescape
func negToAVX512(vOut []uint64, v []uint64, q uint64)

//go:noescape
func mulScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulAddScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulSubScalarWordToAVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulAddScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulSubScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulAddScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulSubScalarToAVX2(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulScalarToAVX2(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulAddScalarToAVX2(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulSubScalarToAVX2(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulScalarToAVX512(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulAddScalarToAVX512(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulSubScalarToAVX512(vOut []uint64, v []uint64, c float64, q uint64, qf float64, qfInv float64)

//go:noescape
func sMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func mulWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubWordToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulAddToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulSubToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func mulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulToAVX2(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulAddToAVX2(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulSubToAVX2(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulToAVX512(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func floatMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []float64, q uint64, qf float64, qfInv float64)

//go:noescape
func sMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func reduceToAVX512(vOut []uint64, v []uint64, q uint64, div uint64, logQ uint64)

//go:noescape
func reduce2QToAVX2(vOut []uint64, v []uint64, q uint64)

//go:noescape
func reduce2QToAVX512(vOut []uint64, v []uint64, q uint64)

//go:noescape
func reduce4QToAVX2(vOut []uint64, v []uint64, q uint64)

//go:noescape
func reduce4QToAVX512(vOut []uint64, v []uint64, q uint64)
