// Code generated by command: go run main.go -vec -out ../../math/mod/asm_vec_ops_amd64.s -stubs ../../math/mod/asm_vec_ops_stub_amd64.go -pkg=mod. DO NOT EDIT.

//go:build amd64 && !purego

package mod

//go:noescape
func addVecToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func addLazyVecToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func subVecToAVX2(v0 []uint64, v1 []uint64, q uint64, vOut []uint64)

//go:noescape
func subLazyVecToAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func mulVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func mulAddVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func mulSubVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func mulLazyVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func mulAddLazyVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)

//go:noescape
func mulSubLazyVecToX86(v0 []uint64, v1 []uint64, q uint64, divHi uint64, divLo uint64, vOut []uint64)
