// Code generated by command: go run main.go -vec -out ../../math/mod/asm_vec_ops_amd64.s -stubs ../../math/mod/asm_vec_ops_stub_amd64.go -pkg=mod. DO NOT EDIT.

//go:build amd64 && !purego

package mod

//go:noescape
func addVecToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addLazyVecToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addVecToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addLazyVecToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subVecToAVX2(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subLazyVecToAVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subVecToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subLazyVecToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
