// Code generated by command: go run asmgen.go -ntt -out ../../math/dft/asm_ntt_pow2.s -stubs ../../math/dft/asm_ntt_pow2_stub_amd64.go -pkg=dft. DO NOT EDIT.

//go:build amd64 && !purego

package dft

//go:noescape
func fwdNTTInPlacePow2UnrollAVX512(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func invNTTInPlacePow2UnrollAVX512(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)
