package crt

import (
	"math/bits"

	"github.com/hienaa-org/hienaa/math/dft"
	"github.com/hienaa-org/hienaa/math/num"
)

// ambientNTTPrimes finds a list of prime moduli that is NTT friendly,
// and its product exceeds 2^minBits.
// minBits is assumed to be finite.
//
// Panics if minBits is not finite or no such primes exist.
func ambientNTTPrimes(params dft.RingParameters, minBits float64) []*num.Modulus {
	gap := dft.NTTPrimeGap(params)
	primes := dft.PrevNTTPrimes(params, num.MaxModulusBits, 1)
	minBits -= float64(bits.Len64(primes[len(primes)-1].Value()) - 1)
	for minBits > 0 {
		primes = append(primes, num.NewModulus(num.PrevPrime(primes[len(primes)-1].Value()-gap, gap)))
		minBits -= float64(bits.Len64(primes[len(primes)-1].Value()) - 1)
	}

	return primes
}

// ambientModLen returns the smallest integer k such that
// product of mod[:k] is greater than or equal to 2^minBits.
// minBits is assumed to be finite.
// Assumes that ambMod was generated by [ambientNTTPrimes],
// and minBits is smaller than minBits used for generating ambMod.
//
// Panics if no such k exists.
func ambientModLen(ambMod []*num.Modulus, minBits float64) int {
	if minBits <= 0 {
		return 0
	}

	for i := range ambMod {
		minBits -= float64(bits.Len64(ambMod[i].Value()) - 1)
		if minBits <= 0 {
			return i + 1
		}
	}

	panic("invalid modulus")
}
