// Code generated by command: go run main.go -ntt -out ../../math/rns/asm_ntt_pow2.s -stubs ../../math/rns/asm_ntt_pow2_stub_amd64.go -pkg=rns. DO NOT EDIT.

//go:build amd64 && !purego

package rns

//go:noescape
func nttInPlacePow2Deg16AVX2(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func nttInPlacePow2Deg16AVX512(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func inttInPlacePow2Deg16AVX2(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)

//go:noescape
func inttInPlacePow2Deg16AVX512(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)
