name: CI Tests
on:
    push:

jobs:
    tests:
        name: Run Go ${{ matrix.go }} Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ["1.21", "1.25"]

        steps:
            - uses: actions/checkout@v5

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}

            - name: Test math/csprng
              run: |
                  go test ./math/csprng -timeout=0 -count=1
                  go test ./math/csprng -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./math/csprng -count=1

            - name: Test math/num
              run: |
                  go test ./math/num -timeout=0 -count=1
                  go test ./math/num -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./math/num -count=1

            - name: Test math/vec
              run: |
                  go test ./math/vec -timeout=0 -count=1
                  go test ./math/vec -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./math/vec -count=1

            - name: Test math/dft
              run: |
                  go test ./math/dft -timeout=0 -count=1
                  go test ./math/dft -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./math/dft -count=1

            - name: Test math/crt
              run: |
                  go test ./math/crt -timeout=0 -count=1
                  go test ./math/crt -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./math/crt -count=1

            - name: Test fhe/rlwe
              run: |
                  go test ./fhe/rlwe -timeout=0 -count=1
                  go test ./fhe/rlwe -timeout=0 -count=1 -tags=purego
                  GODEBUG=cpu.all=off go test ./fhe/rlwe -count=1
